from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = [
    "master"
]
pre = "alpha.*"
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "sbsp"
owner = "Keinsleif"
authors = [
    { username = "Keinsleif", signature = "Keinsleif" },
]

[monorepo.packages.backend]
path = "sbsp_backend"
bump_order = 1
pre_bump_hooks = ["cargo set-version {{version}} -p sbsp_{{package}}"]
public_api = false

[monorepo.packages.frontend]
path = "sbsp_frontend"
bump_order = 2
pre_bump_hooks = ["pnpm version {{version}} --no-git-tag-version --no-git-checks"]
public_api = false

[monorepo.packages.license]
path = "sbsp_license"
bump_order = 3
pre_bump_hooks = ["cargo set-version {{version}} -p sbsp_{{package}}"]
public_api = false

[monorepo.packages.app]
path = "sbsp_app"
include = [
    "sbsp_backend/**",
    "sbsp_frontend/**",
    "sbsp_license/**",
]
bump_order = 4
pre_bump_hooks = ["cargo set-version {{version}} -p sbsp_{{package}}"]

[monorepo.packages.remote_app]
path = "sbsp_remote_app"
include = [
    "sbsp_backend/**",
    "sbsp_frontend/**",
]
bump_order = 5
pre_bump_hooks = ["cargo set-version {{version}} -p sbsp_{{package}}"]
public_api = false

[monorepo.packages.docs]
path = "sbsp_docs"
bump_order = 6
pre_bump_hooks = ["pnpm version {{version}} --no-git-tag-version --no-git-checks"]
public_api = false
