name: bump-version

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: false

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: cocogitto
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto
          git-user: github-actions[bot]
          git-user-email: github-actions[bot]@users.noreply.github.com

      - if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Oh no! Cocogitto failed!  \`\`\`  ${{ steps.cocogitto.outputs.stdout }}  \`\`\`  `
            })

      - name: Push tags
        run: git push --follow-tags
